--------------------------------------------------------
--  File created - czwartek-marca-23-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADRES
--------------------------------------------------------

  CREATE TABLE "S14391"."ADRES" 
   (	"IDADRESU" NUMBER(*,0), 
	"ULICA" CHAR(30 BYTE), 
	"KODPOCZTOWY" CHAR(30 BYTE), 
	"MIEJSCOWOSC" CHAR(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table DOSTAWCA
--------------------------------------------------------

  CREATE TABLE "S14391"."DOSTAWCA" 
   (	"IDDOSTAWCA" NUMBER(*,0), 
	"NAZWA" CHAR(30 BYTE), 
	"ADRESKORESPONDENCYJNY" NUMBER(*,0), 
	"ADRESFAKTURY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table FAKTURA
--------------------------------------------------------

  CREATE TABLE "S14391"."FAKTURA" 
   (	"IDFAKTURA" NUMBER(*,0), 
	"NUMER" CHAR(30 BYTE), 
	"NETTO" NUMBER(*,0), 
	"BRUTTO" NUMBER(*,0), 
	"DATAWYSTAWIENIA" DATE, 
	"TERMINPLATNOSCI" DATE, 
	"CZYZAPLACONA" NUMBER(*,0), 
	"IDPROJEKTU" NUMBER(*,0), 
	"IDHANDLOWCA" NUMBER(*,0), 
	"IDDOSTAWCA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table HANDLOWIEC
--------------------------------------------------------

  CREATE TABLE "S14391"."HANDLOWIEC" 
   (	"IDHANDLOWCA" NUMBER(*,0), 
	"IMIE" CHAR(30 BYTE), 
	"NAZWISKO" CHAR(30 BYTE), 
	"IDADRESU" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table PRACOWNIK
--------------------------------------------------------

  CREATE TABLE "S14391"."PRACOWNIK" 
   (	"IMIE" CHAR(30 BYTE), 
	"NAZWISKO" CHAR(30 BYTE), 
	"PESEL" CHAR(11 BYTE), 
	"IDRODZAJUMOWY" NUMBER(*,0), 
	"IDPRZELOZONEGO" NUMBER(*,0), 
	"IDPRACOWNIKA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table PROJEKT
--------------------------------------------------------

  CREATE TABLE "S14391"."PROJEKT" 
   (	"IDPROJEKTU" NUMBER(*,0), 
	"NAZWA" CHAR(30 BYTE), 
	"DATAPOCZATKU" CHAR(30 BYTE), 
	"DATAKONCA" CHAR(30 BYTE), 
	"ARCHIWALNY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table PROJEKTPRACOWNIK
--------------------------------------------------------

  CREATE TABLE "S14391"."PROJEKTPRACOWNIK" 
   (	"IDPRACOWNIKA" NUMBER(*,0), 
	"IDPROJEKTPRACOWNIK" NUMBER(*,0), 
	"IDPROJEKTU" NUMBER(*,0), 
	"IDTYPUPRACOWNIKA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table PRZYSLUGUJACEDNIWOLNE
--------------------------------------------------------

  CREATE TABLE "S14391"."PRZYSLUGUJACEDNIWOLNE" 
   (	"IDPRACOWNIKA" NUMBER(*,0), 
	"IDPRZYSLUGUJACEDNIWOLNE" NUMBER(*,0), 
	"IDROCZNIKA" NUMBER(*,0), 
	"IDTYPUURLOPU" NUMBER(*,0), 
	"ILOSCDNIOGOLNA" NUMBER(*,0), 
	"ILOSCDNIWYKORZYSTANYCH" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table ROCZNIK
--------------------------------------------------------

  CREATE TABLE "S14391"."ROCZNIK" 
   (	"IDROCZNIKA" NUMBER(*,0), 
	"ROK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table RODZAJUMOWY
--------------------------------------------------------

  CREATE TABLE "S14391"."RODZAJUMOWY" 
   (	"IDRODZAJUMOWY" NUMBER(*,0), 
	"NAZWA" CHAR(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table STATUS
--------------------------------------------------------

  CREATE TABLE "S14391"."STATUS" 
   (	"IDSTATUSU" NUMBER(*,0), 
	"NAZWA" CHAR(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table TYPPRACOWNIKAWPROJEKCIE
--------------------------------------------------------

  CREATE TABLE "S14391"."TYPPRACOWNIKAWPROJEKCIE" 
   (	"IDTYPUPRACOWNIKA" NUMBER(*,0), 
	"NAZWA" CHAR(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table TYPURLOPU
--------------------------------------------------------

  CREATE TABLE "S14391"."TYPURLOPU" 
   (	"IDTYPUURLOPU" NUMBER(*,0), 
	"NAZWA" CHAR(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table URLOP
--------------------------------------------------------

  CREATE TABLE "S14391"."URLOP" 
   (	"IDURLOPU" NUMBER(*,0), 
	"DATA" DATE, 
	"DLUGOSC" NUMBER(*,0), 
	"IDPRZYSLUGUJACEDNIWOLNE" NUMBER(*,0), 
	"IDSTATUSU" NUMBER(*,0), 
	"IDPRACOWNIKA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Table WORKFLOWFAKTURY
--------------------------------------------------------

  CREATE TABLE "S14391"."WORKFLOWFAKTURY" 
   (	"IDPRACOWNIKA" NUMBER(*,0), 
	"IDWORKFLOWFAKTURY" NUMBER(*,0), 
	"IDPROJEKTPRACOWNIK" NUMBER(*,0), 
	"IDFAKTURA" NUMBER(*,0), 
	"POTWIERDZENIE" NUMBER(*,0), 
	"DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index ADRES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."ADRES_PK" ON "S14391"."ADRES" ("IDADRESU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index DOSTAWCA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."DOSTAWCA_PK" ON "S14391"."DOSTAWCA" ("IDDOSTAWCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index FAKTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."FAKTURA_PK" ON "S14391"."FAKTURA" ("IDFAKTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index HANDLOWIEC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."HANDLOWIEC_PK" ON "S14391"."HANDLOWIEC" ("IDHANDLOWCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index PRACOWNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."PRACOWNIK_PK" ON "S14391"."PRACOWNIK" ("IDPRACOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index PROJEKT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."PROJEKT_PK" ON "S14391"."PROJEKT" ("IDPROJEKTU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index PROJEKTPRACOWNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."PROJEKTPRACOWNIK_PK" ON "S14391"."PROJEKTPRACOWNIK" ("IDPRACOWNIKA", "IDPROJEKTPRACOWNIK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index PRZYSLUGUJACEDNIWOLNE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."PRZYSLUGUJACEDNIWOLNE_PK" ON "S14391"."PRZYSLUGUJACEDNIWOLNE" ("IDPRACOWNIKA", "IDPRZYSLUGUJACEDNIWOLNE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index ROCZNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."ROCZNIK_PK" ON "S14391"."ROCZNIK" ("IDROCZNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index RODZAJUMOWY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."RODZAJUMOWY_PK" ON "S14391"."RODZAJUMOWY" ("IDRODZAJUMOWY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."STATUS_PK" ON "S14391"."STATUS" ("IDSTATUSU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index TYPPRACOWNIKAWPROJEKCIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."TYPPRACOWNIKAWPROJEKCIE_PK" ON "S14391"."TYPPRACOWNIKAWPROJEKCIE" ("IDTYPUPRACOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index TYPURLOPU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."TYPURLOPU_PK" ON "S14391"."TYPURLOPU" ("IDTYPUURLOPU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index URLOP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."URLOP_PK" ON "S14391"."URLOP" ("IDURLOPU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  DDL for Index WORKFLOWFAKTURY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S14391"."WORKFLOWFAKTURY_PK" ON "S14391"."WORKFLOWFAKTURY" ("IDPRACOWNIKA", "IDWORKFLOWFAKTURY", "IDPROJEKTPRACOWNIK", "IDFAKTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI" ;
--------------------------------------------------------
--  Constraints for Table ADRES
--------------------------------------------------------

  ALTER TABLE "S14391"."ADRES" ADD CONSTRAINT "ADRES_PK" PRIMARY KEY ("IDADRESU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."ADRES" MODIFY ("IDADRESU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."ADRES" MODIFY ("ULICA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."ADRES" MODIFY ("KODPOCZTOWY" NOT NULL ENABLE);
  ALTER TABLE "S14391"."ADRES" MODIFY ("MIEJSCOWOSC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOSTAWCA
--------------------------------------------------------

  ALTER TABLE "S14391"."DOSTAWCA" ADD CONSTRAINT "DOSTAWCA_PK" PRIMARY KEY ("IDDOSTAWCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."DOSTAWCA" MODIFY ("IDDOSTAWCA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."DOSTAWCA" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."DOSTAWCA" MODIFY ("ADRESKORESPONDENCYJNY" NOT NULL ENABLE);
  ALTER TABLE "S14391"."DOSTAWCA" MODIFY ("ADRESFAKTURY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FAKTURA
--------------------------------------------------------

  ALTER TABLE "S14391"."FAKTURA" ADD CONSTRAINT "FAKTURA_PK" PRIMARY KEY ("IDFAKTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("IDFAKTURA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("NUMER" NOT NULL ENABLE);
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("NETTO" NOT NULL ENABLE);
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("BRUTTO" NOT NULL ENABLE);
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("DATAWYSTAWIENIA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("TERMINPLATNOSCI" NOT NULL ENABLE);
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("CZYZAPLACONA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("IDPROJEKTU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("IDHANDLOWCA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."FAKTURA" MODIFY ("IDDOSTAWCA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HANDLOWIEC
--------------------------------------------------------

  ALTER TABLE "S14391"."HANDLOWIEC" ADD CONSTRAINT "HANDLOWIEC_PK" PRIMARY KEY ("IDHANDLOWCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."HANDLOWIEC" MODIFY ("IDHANDLOWCA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."HANDLOWIEC" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "S14391"."HANDLOWIEC" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "S14391"."HANDLOWIEC" MODIFY ("IDADRESU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRACOWNIK
--------------------------------------------------------

  ALTER TABLE "S14391"."PRACOWNIK" ADD CONSTRAINT "PRACOWNIK_PK" PRIMARY KEY ("IDPRACOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."PRACOWNIK" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRACOWNIK" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRACOWNIK" MODIFY ("PESEL" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRACOWNIK" MODIFY ("IDRODZAJUMOWY" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRACOWNIK" MODIFY ("IDPRZELOZONEGO" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRACOWNIK" MODIFY ("IDPRACOWNIKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJEKT
--------------------------------------------------------

  ALTER TABLE "S14391"."PROJEKT" ADD CONSTRAINT "PROJEKT_PK" PRIMARY KEY ("IDPROJEKTU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."PROJEKT" MODIFY ("IDPROJEKTU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PROJEKT" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PROJEKT" MODIFY ("DATAPOCZATKU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PROJEKT" MODIFY ("DATAKONCA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PROJEKT" MODIFY ("ARCHIWALNY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJEKTPRACOWNIK
--------------------------------------------------------

  ALTER TABLE "S14391"."PROJEKTPRACOWNIK" ADD CONSTRAINT "PROJEKTPRACOWNIK_PK" PRIMARY KEY ("IDPRACOWNIKA", "IDPROJEKTPRACOWNIK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."PROJEKTPRACOWNIK" MODIFY ("IDPRACOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PROJEKTPRACOWNIK" MODIFY ("IDPROJEKTPRACOWNIK" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PROJEKTPRACOWNIK" MODIFY ("IDPROJEKTU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PROJEKTPRACOWNIK" MODIFY ("IDTYPUPRACOWNIKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRZYSLUGUJACEDNIWOLNE
--------------------------------------------------------

  ALTER TABLE "S14391"."PRZYSLUGUJACEDNIWOLNE" ADD CONSTRAINT "PRZYSLUGUJACEDNIWOLNE_PK" PRIMARY KEY ("IDPRACOWNIKA", "IDPRZYSLUGUJACEDNIWOLNE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."PRZYSLUGUJACEDNIWOLNE" MODIFY ("IDPRACOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRZYSLUGUJACEDNIWOLNE" MODIFY ("IDPRZYSLUGUJACEDNIWOLNE" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRZYSLUGUJACEDNIWOLNE" MODIFY ("IDROCZNIKA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRZYSLUGUJACEDNIWOLNE" MODIFY ("IDTYPUURLOPU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRZYSLUGUJACEDNIWOLNE" MODIFY ("ILOSCDNIOGOLNA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."PRZYSLUGUJACEDNIWOLNE" MODIFY ("ILOSCDNIWYKORZYSTANYCH" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROCZNIK
--------------------------------------------------------

  ALTER TABLE "S14391"."ROCZNIK" ADD CONSTRAINT "ROCZNIK_PK" PRIMARY KEY ("IDROCZNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."ROCZNIK" MODIFY ("IDROCZNIKA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."ROCZNIK" MODIFY ("ROK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RODZAJUMOWY
--------------------------------------------------------

  ALTER TABLE "S14391"."RODZAJUMOWY" ADD CONSTRAINT "RODZAJUMOWY_PK" PRIMARY KEY ("IDRODZAJUMOWY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."RODZAJUMOWY" MODIFY ("IDRODZAJUMOWY" NOT NULL ENABLE);
  ALTER TABLE "S14391"."RODZAJUMOWY" MODIFY ("NAZWA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUS
--------------------------------------------------------

  ALTER TABLE "S14391"."STATUS" ADD CONSTRAINT "STATUS_PK" PRIMARY KEY ("IDSTATUSU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
  ALTER TABLE "S14391"."STATUS" MODIFY ("IDSTATUSU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."STATUS" MODIFY ("NAZWA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPPRACOWNIKAWPROJEKCIE
--------------------------------------------------------

  ALTER TABLE "S14391"."TYPPRACOWNIKAWPROJEKCIE" MODIFY ("IDTYPUPRACOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."TYPPRACOWNIKAWPROJEKCIE" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."TYPPRACOWNIKAWPROJEKCIE" ADD CONSTRAINT "TYPPRACOWNIKAWPROJEKCIE_PK" PRIMARY KEY ("IDTYPUPRACOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TYPURLOPU
--------------------------------------------------------

  ALTER TABLE "S14391"."TYPURLOPU" MODIFY ("IDTYPUURLOPU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."TYPURLOPU" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."TYPURLOPU" ADD CONSTRAINT "TYPURLOPU_PK" PRIMARY KEY ("IDTYPUURLOPU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table URLOP
--------------------------------------------------------

  ALTER TABLE "S14391"."URLOP" MODIFY ("IDURLOPU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."URLOP" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."URLOP" MODIFY ("DLUGOSC" NOT NULL ENABLE);
  ALTER TABLE "S14391"."URLOP" MODIFY ("IDPRZYSLUGUJACEDNIWOLNE" NOT NULL ENABLE);
  ALTER TABLE "S14391"."URLOP" MODIFY ("IDSTATUSU" NOT NULL ENABLE);
  ALTER TABLE "S14391"."URLOP" MODIFY ("IDPRACOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."URLOP" ADD CONSTRAINT "URLOP_PK" PRIMARY KEY ("IDURLOPU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKFLOWFAKTURY
--------------------------------------------------------

  ALTER TABLE "S14391"."WORKFLOWFAKTURY" MODIFY ("IDPRACOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."WORKFLOWFAKTURY" MODIFY ("IDWORKFLOWFAKTURY" NOT NULL ENABLE);
  ALTER TABLE "S14391"."WORKFLOWFAKTURY" MODIFY ("IDPROJEKTPRACOWNIK" NOT NULL ENABLE);
  ALTER TABLE "S14391"."WORKFLOWFAKTURY" MODIFY ("IDFAKTURA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."WORKFLOWFAKTURY" MODIFY ("POTWIERDZENIE" NOT NULL ENABLE);
  ALTER TABLE "S14391"."WORKFLOWFAKTURY" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "S14391"."WORKFLOWFAKTURY" ADD CONSTRAINT "WORKFLOWFAKTURY_PK" PRIMARY KEY ("IDPRACOWNIKA", "IDWORKFLOWFAKTURY", "IDPROJEKTPRACOWNIK", "IDFAKTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENCI"  ENABLE;
